### ISSUE TITLE
Request a license?

### ISSUE THREAD

**Issue by perkinsms** [byung806/TroopWebHost-Improvement-Project#1]
I am also working in this space - see tm_parser on pypi, scoutbook_parser on pypi, and django-troop on gitlab. 

Could you put a license for your code so I can figure out how we can work together? 

Yours
Michael Perkins

**Comment by byung806** [comment]
Thanks for sharing! I took a look at your projects and they look very similar.
I just updated the README and added a LICENSE. We can discuss future plans for sure.

Sorry for the late reply.
